export default [
  // 'assets/tank_basis/tank_basis.json',
  'assets/human_idle/human_idle.json',
  'assets/human_fire/human_fire.json',
  'assets/human_run/human_run.json',
  'assets/human_hit/s_h.json',
  'assets/human_getup/s_gu.json',
  'assets/fire_effect/fireEffect.json',
  // 'assets/laser_effect/laserEffect.json',
  'assets/generic_selection.png',
  // 'assets/warrior_idle/warrior_idle.json',
  // 'assets/warrior_fire/w_f.json',
  // 'assets/warrior_hit/w_h.json',
  // 'assets/warrior_getup/w_gu.json',
  // 'assets/warrior_run/warrior_run.json',
  // 'assets/warrior_assault_run/a_r.json',
  // 'assets/warrior_assault_fire/a_f.json',
  // 'assets/warrior_assault_idle/a_i.json',
  'assets/grenade-icon.png',
  'assets/jump-icon.png',
  'assets/portal_fx/portal_fx.json',
  'assets/gate/gate.json',
  'assets/Fire.png',
  'assets/smoke.png',

  // 'assets/warriorAssaultAvatar.png',
  // 'assets/warriorRegularAvatar.png',
  'assets/soliderLaserAvatar.png',
  'assets/soliderRegularAvatar.png',
  'assets/ability_progress_bar.png',
  'assets/grenade_icon_blue.png',
  'assets/grenade_icon_blue_hover.png',
  'assets/wing_icon_blue.png',
  'assets/wing_icon_blue_hover.png',
  'assets/start_btn.png',
  'assets/donate_btn.png',
  'assets/pure_background_with_traced_images.jpg',
  'assets/divider.png',
  'assets/btnStartHover.png',


  'assets/units/troop-body/troop-body-run.json',
  'assets/units/troop-body/troop-body-idle.json',
  'assets/units/troop-body/troop-body-fly.json',
  'assets/units/troop-body/troop-body-getup.json',
  'assets/units/troop-body/troop-body-shoot.json',

  'assets/units/troop-regular-accessories/regular-accessories-run.json',
  'assets/units/troop-regular-accessories/regular-accessories-idle.json',
  'assets/units/troop-regular-accessories/regular-accessories-fly.json',
  'assets/units/troop-regular-accessories/regular-accessories-getup.json',
  'assets/units/troop-regular-accessories/regular-accessories-shoot.json',
  'assets/units/troop-regular-accessories/regular-accessories-chasing.json',

  'assets/units/rodion-head/rodion-head-shoot.json',
  'assets/units/rodion-head/rodion-head-run.json',
  'assets/units/rodion-head/rodion-head-getup.json',
  'assets/units/rodion-head/rodion-head-fly.json',
  'assets/units/rodion-head/rodion-head-idle.json',
  
  'assets/units/elephant-head/elephant-head-shoot.json',
  'assets/units/elephant-head/elephant-head-run.json',
  'assets/units/elephant-head/elephant-head-getup.json',
  'assets/units/elephant-head/elephant-head-fly.json',
  'assets/units/elephant-head/elephant-head-idle.json',
  
  'assets/buildings/portal/portal-bottom-base.json',
  'assets/buildings/portal/portal-dynamic-wing.json',
  'assets/buildings/portal/portal-lights.json',
  'assets/buildings/portal/portal-static-wing.json',
  'assets/buildings/portal/portal-top-base.json',

  'assets/bridge/adornment.json',
  'assets/bridge/boundary-stick.json',
  'assets/bridge/track-side.jpg',
  'assets/bridge/track-surface.jpg',

  // 'assets/clouds/clouds.json',
  'assets/cloud-tail-2-cropped.png',
  'assets/node-platform.png',
  'assets/node-platform-shaded.png',
]
