export enum STATE {
  ABILITY = 8,
  FLY = 7,
  GO = 6,

  SHOOT = 5,
  STAY = 4,
  GETUP = 3,
  DIE = 0,
}

export enum UNIT_TYPE {
  WARRIOR_REGULAR = 'WARRIOR_REGULAR',
  SOLIDER_REGULAR = 'SOLIDER_REGULAR',
  SOLIDER_LASER = 'SOLIDER_LASER',
  WARRIOR_ASSAULT = 'WARRIOR_ASSAULT',
}
