pub const MATH_PI: f32 = std::f32::consts::PI;
pub const MAX_NUMBER_ITEMS_IN_PRODUCTION_LINE: usize = 5;
pub const NORMAL_SQUAD_RADIUS: f32 = 60.0;
pub const MAX_SQUAD_SPREAD_FROM_CENTER_RADIUS: f32 = NORMAL_SQUAD_RADIUS + 100.0;
pub const THRESHOLD_MAX_UNIT_DISTANCE_FROM_SQUAD_CENTER: f32 =
  MAX_SQUAD_SPREAD_FROM_CENTER_RADIUS + 100.0; // above this distance squad is recognized as too far

pub const UPDATE_SQUAD_CENTER_PERIOD: u32 = 15;
pub const CHECK_SQUADS_CORRECTNESS_PERIOD: u32 = 2 * UPDATE_SQUAD_CENTER_PERIOD;
pub const MANAGE_HUNTERS_PERIOD: u32 = 3 * CHECK_SQUADS_CORRECTNESS_PERIOD;
pub const AI_CALCULATION_PERIOD: u32 = 2 * MANAGE_HUNTERS_PERIOD;

pub const MAP_WIDTH: f32 = 2700.0;
pub const MAP_HEIGHT: f32 = 2100.0;

pub const GRID_CELL_SIZE: f32 = 300.0;
const GRID_MAP_SCALE: f32 = 1.0 / GRID_CELL_SIZE;
pub const GRID_MAP_WIDTH: usize = (MAP_WIDTH * GRID_MAP_SCALE + 1.0) as usize;
pub const GRID_MAP_HEIGHT: usize = (MAP_HEIGHT * GRID_MAP_SCALE + 1.0) as usize;
pub const GRID_MAP_SCALE_X: f32 = GRID_MAP_WIDTH as f32 / MAP_WIDTH;
pub const GRID_MAP_SCALE_Y: f32 = GRID_MAP_HEIGHT as f32 / MAP_HEIGHT;
pub const GRID_MAP_SCALE_AVG: f32 = (GRID_MAP_SCALE_X + GRID_MAP_SCALE_Y) / 2.0; // to scale the radius stuff like weapon range

pub const OBSTACLES_CELL_SIZE: f32 = 20.0; // remember to change also in debug/obstaclesMap.ts
const OBSTACLES_MAP_SCALE: f32 = 1.0 / OBSTACLES_CELL_SIZE;
pub const OBSTACLES_MAP_WIDTH: usize = (MAP_WIDTH * OBSTACLES_MAP_SCALE + 1.0) as usize;
pub const OBSTACLES_MAP_HEIGHT: usize = (MAP_HEIGHT * OBSTACLES_MAP_SCALE + 1.0) as usize;
pub const OBSTACLES_MAP_SCALE_X: f32 = OBSTACLES_MAP_WIDTH as f32 / MAP_WIDTH;
pub const OBSTACLES_MAP_SCALE_Y: f32 = OBSTACLES_MAP_HEIGHT as f32 / MAP_HEIGHT;
