pub const FACTION_REPRESENTATION_ID: f32 = 0.0;
pub const ENEMY_FACTORY_REPRESENTATION_ID: f32 = 1.0;
pub const SOLIDER_REPRESENTATION_ID: f32 = 2.0;
pub const USER_FACTORY_REPRESENTATION_ID: f32 = 3.0;
pub const BULLETS_REPRESENTATION_ID: f32 = 4.0;
pub const RAPTOR_REPRESENTATION_ID: f32 = 5.0;
